[2025-06-23T05:58:30.541+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-23T05:58:30.611+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stream_dag.dbt_test scheduled__2025-06-23T05:56:00+00:00 [queued]>
[2025-06-23T05:58:30.626+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stream_dag.dbt_test scheduled__2025-06-23T05:56:00+00:00 [queued]>
[2025-06-23T05:58:30.628+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-23T05:58:30.663+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2025-06-23 05:56:00+00:00
[2025-06-23T05:58:30.693+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=144) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-23T05:58:30.696+0000] {standard_task_runner.py:64} INFO - Started process 148 to run task
[2025-06-23T05:58:30.693+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stream_dag', 'dbt_test', 'scheduled__2025-06-23T05:56:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/stream_dag.py', '--cfg-path', '/tmp/tmpm4iwxw2k']
[2025-06-23T05:58:30.698+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask dbt_test
[2025-06-23T05:58:30.790+0000] {task_command.py:426} INFO - Running <TaskInstance: stream_dag.dbt_test scheduled__2025-06-23T05:56:00+00:00 [running]> on host b2b82406f119
[2025-06-23T05:58:31.167+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Sharaf' AIRFLOW_CTX_DAG_ID='stream_dag' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-06-23T05:56:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-23T05:56:00+00:00'
[2025-06-23T05:58:31.173+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-23T05:58:31.182+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-23T05:58:31.193+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt_ && dbt test']
[2025-06-23T05:58:31.370+0000] {subprocess.py:86} INFO - Output:
[2025-06-23T05:58:42.811+0000] {subprocess.py:93} INFO - [0m05:58:42  Running with dbt=1.10.2
[2025-06-23T05:58:56.493+0000] {subprocess.py:93} INFO - [0m05:58:56  Registered adapter: snowflake=1.9.4
[2025-06-23T05:59:00.778+0000] {subprocess.py:93} INFO - [0m05:59:00  Encountered an error:
[2025-06-23T05:59:00.781+0000] {subprocess.py:93} INFO - [Errno 22] Invalid argument: '/opt/***/dbt_/target/manifest.json'
[2025-06-23T05:59:00.801+0000] {subprocess.py:93} INFO - [0m05:59:00  Traceback (most recent call last):
[2025-06-23T05:59:00.803+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 161, in wrapper
[2025-06-23T05:59:00.805+0000] {subprocess.py:93} INFO -     result, success = func(*args, **kwargs)
[2025-06-23T05:59:00.806+0000] {subprocess.py:93} INFO -                       ^^^^^^^^^^^^^^^^^^^^^
[2025-06-23T05:59:00.808+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 111, in wrapper
[2025-06-23T05:59:00.811+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-06-23T05:59:00.813+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-06-23T05:59:00.816+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 254, in wrapper
[2025-06-23T05:59:00.818+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-06-23T05:59:00.820+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-06-23T05:59:00.822+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 285, in wrapper
[2025-06-23T05:59:00.823+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-06-23T05:59:00.825+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-06-23T05:59:00.828+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 332, in wrapper
[2025-06-23T05:59:00.830+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-06-23T05:59:00.832+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-06-23T05:59:00.833+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 371, in wrapper
[2025-06-23T05:59:00.835+0000] {subprocess.py:93} INFO -     setup_manifest(ctx, write=write, write_perf_info=write_perf_info)
[2025-06-23T05:59:00.836+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 398, in setup_manifest
[2025-06-23T05:59:00.837+0000] {subprocess.py:93} INFO -     ctx.obj["manifest"] = parse_manifest(
[2025-06-23T05:59:00.838+0000] {subprocess.py:93} INFO -                           ^^^^^^^^^^^^^^^
[2025-06-23T05:59:00.839+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 2122, in parse_manifest
[2025-06-23T05:59:00.840+0000] {subprocess.py:93} INFO -     write_manifest(manifest, runtime_config.project_target_path)
[2025-06-23T05:59:00.841+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 2100, in write_manifest
[2025-06-23T05:59:00.846+0000] {subprocess.py:93} INFO -     manifest.write(path)
[2025-06-23T05:59:00.847+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/contracts/graph/manifest.py", line 1231, in write
[2025-06-23T05:59:00.848+0000] {subprocess.py:93} INFO -     writable.write(path)
[2025-06-23T05:59:00.849+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/artifacts/schemas/base.py", line 36, in write
[2025-06-23T05:59:00.850+0000] {subprocess.py:93} INFO -     write_json(path, self.to_dict(omit_none=False, context={"artifact": True}))  # type: ignore
[2025-06-23T05:59:00.852+0000] {subprocess.py:93} INFO -     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-06-23T05:59:00.853+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt_common/clients/system.py", line 305, in write_json
[2025-06-23T05:59:00.854+0000] {subprocess.py:93} INFO -     with open(path, "w", encoding="utf-8") as f:
[2025-06-23T05:59:00.856+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-06-23T05:59:00.857+0000] {subprocess.py:93} INFO - OSError: [Errno 22] Invalid argument: '/opt/***/dbt_/target/manifest.json'
[2025-06-23T05:59:00.859+0000] {subprocess.py:93} INFO - 
[2025-06-23T05:59:04.503+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-06-23T05:59:04.519+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-23T05:59:04.821+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-06-23T05:59:04.975+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stream_dag, task_id=dbt_test, run_id=scheduled__2025-06-23T05:56:00+00:00, execution_date=20250623T055600, start_date=20250623T055830, end_date=20250623T055904
[2025-06-23T05:59:05.187+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task dbt_test (Bash command failed. The command returned a non-zero exit code 2.; 148)
[2025-06-23T05:59:05.341+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-06-23T05:59:06.026+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-23T05:59:06.035+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
